### ISSUE TITLE
不好意思請問一下有關翻譯語言部分

### ISSUE THREAD

**Issue by BlackZoneJweak** [abse4411/projz_renpy#2]
Abse4411 大大 您好 不好意思，我剛學編程可是我想編輯英文到西文或是葡萄牙文不知道是要修改哪裡，我沒有找到所以才來詢問您 不好意思，希望您可以教教我，謝謝

**Comment by abse4411** [comment]
> Abse4411 大大 您好 不好意思，我剛學編程可是我想編輯英文到西文或是葡萄牙文不知道是要修改哪裡，我沒有找到所以才來詢問您 不好意思，希望您可以教教我，謝謝

这是理论可以实现的，但是具体能支持语言这仍由翻译网站决定。假设你的翻译目标为：英语->西班牙语，首先你需要在 [这里](https://github.com/abse4411/projz_renpy/blob/83d9f3b5d3e448907cc174ef0f26fcd803f86e50/incre_parse.py#L126C1-L129C56)将这个条件去掉 `contain_alpha(raw_text)`因为认为它认为如果不是含有英文字母的字符串才会加入翻译：
```python
      if tran_text == raw_text and contain_alpha(raw_text):
          # add special marks to the untranslated text,
          # please remove these marks before translating the raw text in the next phase
          tran_text = "@$" + raw_text
```
变为：
```python
      if tran_text == raw_text: # 修改在这
          # add special marks to the untranslated text,
          # please remove these marks before translating the raw text in the next phase
          tran_text = "@$" + raw_text
```
接着，假如你选择caiyun作为翻译引擎，在[这里](https://github.com/abse4411/projz_renpy/blob/83d9f3b5d3e448907cc174ef0f26fcd803f86e50/trans/web_trans.py#L114C1-L122C79)修改它的启动延迟，将它改为10s或者更长
```python
class caiyun(web_translator):
    def __init__(self, driver_path):
        super().__init__(driver_path)
        self.browser.get('https://fanyi.caiyunapp.com/')
        print('等待网页加载...')
        time.sleep(5)
        ActionChains(self.browser).move_by_offset(0, 0).click().perform()
        # inputArea = browser.find_element_by_class_name('textinput')
        self.inputArea = self.browser.find_element(By.CLASS_NAME, 'textinput')
```
变为
```python
class caiyun(web_translator):
    def __init__(self, driver_path):
        super().__init__(driver_path)
        self.browser.get('https://fanyi.caiyunapp.com/')
        print('等待网页加载...')
        time.sleep(10) # 修改在这
        ActionChains(self.browser).move_by_offset(0, 0).click().perform()
        # inputArea = browser.find_element_by_class_name('textinput')
        self.inputArea = self.browser.find_element(By.CLASS_NAME, 'textinput')
```
当运行`paese.py`, 选择请指定翻译引擎caiyun（`--trans_api caiyun`）。程序运行后会启动浏览器，这可以为你保留更多的时间选择翻译的目标，这里把源语言改成英文，目标语言改西班牙语：
<img width="545" alt="image" src="https://github.com/abse4411/projz_renpy/assets/29497928/33d474eb-cf68-4e6d-94b2-125160d3100d">
之后就不需要操作等待程序自动执行即可，因此能支持的语言取决翻译网站。

**Comment by BlackZoneJweak** [comment]
谢谢Abse4411大大的教学︿︿ 还有一个问题请问一下，正常翻译一个游戏的时间大约是多少？ 不好意思新手第一次接触renpy游戏编码很多东西都不懂 ^^

**Comment by BlackZoneJweak** [comment]
大大 不好意思喔 我照著您的教学，一直都到5.1.3都没有问题，有出现机翻特殊标记文本,执行5.2.2后，有出现google视窗，有抓英文有看到翻译，可是结束后，去看机翻的rpy还是英文 Orz 是我哪里设定错误吗？ 不好意思一直麻烦您，我还在努力研究中，我目前是翻译一个新的游戏，没有旧的本，作业系统windows 11繁体中文跟西文 python 3.11 这是我的电脑配备，我的中文不太好xD 这里附上我的python输出画面 谢谢大大喔 在一次不好意思 麻烦您了[https://upload.cc/i1/2023/07/28/IFe09C.png](url)

**Comment by abse4411** [comment]
> 谢谢Abse4411大大的教学︿︿ 还有一个问题请问一下，正常翻译一个游戏的时间大约是多少？ 不好意思新手第一次接触renpy游戏编码很多东西都不懂 ^^

这取决游戏的文本数量，在运行`parse.py`可以显示每个文件翻译用时，在最后会显示总花费的时间。实际上，你可把文件拆分到多个文件夹，启动多个`parse.py`，并分别指定多个文件，这相当于多进程，可以大大缩短翻译时间。

**Comment by abse4411** [comment]
> 大大 不好意思喔 我照著您的教学，一直都到5.1.3都没有问题，有出现机翻特殊标记文本,执行5.2.2后，有出现google视窗，有抓英文有看到翻译，可是结束后，去看机翻的rpy还是英文 Orz 是我哪里设定错误吗？ 不好意思一直麻烦您，我还在努力研究中，我目前是翻译一个新的游戏，没有旧的本，作业系统windows 11繁体中文跟西文 python 3.11 这是我的电脑配备，我的中文不太好xD 这里附上我的python输出画面 谢谢大大喔 在一次不好意思 麻烦您了https://upload.cc/i1/2023/07/28/IFe09C.png

你好，可以试英文交流也没问题。这张图像似乎无法看出问题所在。我看了一下google翻译网站，网站似乎做了点变动，可能导致翻译结果获取有问题。你可以给出你的联系方式（email或者其他的），这样我可及时帮你解决。
Hi, it's seen that this image doesn't provide useful information. For further helping, you can leave your email or other ways I can contact with you. ;-)

**Comment by BlackZoneJweak** [comment]
谢谢Abse4411大大 刚刚好练习中文，我在南美洲我们大多是都用西班牙文或是葡萄牙文，所以刚刚好练习中文只是怕中文表达的不好，有关翻译的时间了解了，我的email: onizukacoolsc@gmail.com Discord: 871210154023075890 xD 在麻烦您了
google翻译网站做了变动？请问您是在哪里看到的官网? 谢谢喔

**Comment by abse4411** [comment]
> 大大 不好意思喔 我照著您的教学，一直都到5.1.3都没有问题，有出现机翻特殊标记文本,执行5.2.2后，有出现google视窗，有抓英文有看到翻译，可是结束后，去看机翻的rpy还是英文 Orz 是我哪里设定错误吗？ 不好意思一直麻烦您，我还在努力研究中，我目前是翻译一个新的游戏，没有旧的本，作业系统windows 11繁体中文跟西文 python 3.11 这是我的电脑配备，我的中文不太好xD 这里附上我的python输出画面 谢谢大大喔 在一次不好意思 麻烦您了https://upload.cc/i1/2023/07/28/IFe09C.png

我已经提交一个commit。它修复了google翻译问题，在我的电脑上已经测试通过。你可以拉取最新的代码来完成你的工作。
A commit has been pushed to fix your mentioned problem. This commit was tested. Try to pull new code to continue your work.

**Comment by BlackZoneJweak** [comment]
感恩喔，谢谢喔 。来去下载， 晚点下班后，来跟以前的做对比，谢谢您让我python的编码的知识不断的成长 xD

**Comment by abse4411** [comment]
> 感恩喔，谢谢喔 。来去下载， 晚点下班后，来跟以前的做对比，谢谢您让我python的编码的知识不断的成长 xD

拉取新的代码后，记得重新按照[这里](https://github.com/abse4411/projz_renpy/issues/2#issuecomment-1652866355)指引。
You're welcome. Please follow this [guide](https://github.com/abse4411/projz_renpy/issues/2#issuecomment-1652866355) to modify you code. (See my first comment in this issue.)  Have a nice day!
